"""
Typed access to build/facts.sqlite + entity resolution for Vietnamese admissions questions.

Numbers shown to students (cut-off scores, quotas, tuition) are ALWAYS read from here,
never generated by the LLM or copied from retrieved text.
"""

from __future__ import annotations

import re
import sqlite3
import threading
from dataclasses import asdict, dataclass, field
from functools import lru_cache

from config.settings import get_settings
from knowledge.text import normalize, strip_accents

_lock = threading.Lock()

# Program detection on accent-free lowercase text; order matters (most specific first).
PROGRAM_PATTERNS: list[tuple[str, str]] = [
    ("chuyen_tiep_nhat_ban", r"chuyen tiep (quoc te )?nhat"),
    ("dinh_huong_nhat", r"dinh huong nhat|\bnhat ban\b"),
    ("lien_ket_tne", r"lien ket|\buts\b|\btne\b|sydney"),
    ("chuyen_tiep_quoc_te", r"chuyen tiep|du hoc (uc|my|new zealand|chau au)"),
    ("tien_tien", r"tien tien"),
    ("tieng_anh", r"(chuong trinh|he|\bct|hoc|day|giang day)( va hoc)? (bang )?tieng anh|chat luong cao|\bclc\b"),
    ("pfiev", r"pfiev|viet[ -]phap"),
    ("tai_nang", r"tai nang"),
    ("tieu_chuan", r"tieu chuan|dai tra|he thuong|chuong trinh thuong"),
]
CASE_SENSITIVE_ALIASES = {"AI": "Trí tuệ Nhân tạo", "IT": "Công nghệ Thông tin", "CS": "Khoa học Máy tính"}
METHOD_PATTERNS = [("UTXT", r"\butxt\b|uu tien xet tuyen"), ("TH", r"tong hop|\bth\b")]


@dataclass
class Entities:
    major_ids: list[str] = field(default_factory=list)
    program_ids: list[str] = field(default_factory=list)
    years: list[int] = field(default_factory=list)
    methods: list[str] = field(default_factory=list)
    mentioned_scores: list[float] = field(default_factory=list)

    def key(self) -> str:
        """Canonical entity signature — used to guard the semantic cache."""
        return "|".join([",".join(sorted(self.major_ids)), ",".join(sorted(self.program_ids)),
                         ",".join(map(str, sorted(self.years))), ",".join(sorted(self.methods))])

    def to_dict(self) -> dict:
        return asdict(self)


def _connect() -> sqlite3.Connection:
    path = get_settings().facts_db_path
    if not path.exists():
        raise FileNotFoundError(f"{path} missing — run `python -m datahub all`.")
    con = sqlite3.connect(f"file:{path}?mode=ro", uri=True, check_same_thread=False)
    con.row_factory = sqlite3.Row
    return con


@lru_cache(maxsize=1)
def _con() -> sqlite3.Connection:
    return _connect()


def query(sql: str, params: tuple | list = ()) -> list[dict]:
    with _lock:
        return [dict(r) for r in _con().execute(sql, params).fetchall()]


def reload() -> None:
    """Call after `datahub build` swaps the DB file."""
    _con.cache_clear()
    _majors.cache_clear()
    _major_aliases.cache_clear()
    latest_year.cache_clear()


@lru_cache(maxsize=1)
def _majors() -> list[dict]:
    return query("SELECT m.*, p.name AS program_name FROM majors m JOIN programs p USING(program_id)")


@lru_cache(maxsize=1)
def _major_aliases() -> list[tuple[str, list[str]]]:
    """(alias_accent_free, [major_ids]) sorted longest-first."""
    majors = _majors()
    out: dict[str, set[str]] = {}
    for row in query("SELECT alias, kind, target FROM aliases"):
        alias = strip_accents(normalize(row["alias"]))
        if len(alias) < 2 or alias.isdigit():
            continue
        if row["kind"] == "major_name":
            out.setdefault(alias, set()).add(row["target"])
        elif row["kind"] == "major":
            target = normalize(row["target"])
            hits = {m["major_id"] for m in majors
                    if target in normalize(m["name"]) or target in normalize(m["specializations"] or "")}
            if hits:
                out.setdefault(alias, set()).update(hits)
    # Students drop the "Chuyên ngành / Nhóm ngành" prefix: the bare name must still win over shorter, broader names
    # ("Công nghệ Sinh học số" → 254, not "Công nghệ Sinh học" → 218). Longest-first matching does the rest.
    for m in majors:
        bare_text = normalize(re.sub(r"^(Chuyên ngành|Nhóm ngành)\s+", "", m["name"]))
        bare = strip_accents(bare_text)
        if len(bare) >= 6 and bare not in out:  # new aliases only; each covers every major whose name/specializations contain it
            out.setdefault(bare, set()).update(
                x["major_id"] for x in majors if bare_text in normalize(x["name"]) or bare_text in normalize(x["specializations"] or ""))
    return sorted(((a, sorted(ids)) for a, ids in out.items()), key=lambda x: -len(x[0]))


@lru_cache(maxsize=1)
def latest_year() -> int:
    return int(query("SELECT MAX(year) AS y FROM admission_scores")[0]["y"])


def resolve(text: str) -> Entities:
    ent = Entities()
    norm = normalize(text)
    flat = strip_accents(norm)
    majors = _majors()
    codes = {m["major_code"] for m in majors}

    for pid, pat in PROGRAM_PATTERNS:
        if re.search(pat, flat) and pid not in ent.program_ids:
            if pid in ("dinh_huong_nhat", "chuyen_tiep_quoc_te") and "chuyen_tiep_nhat_ban" in ent.program_ids:
                continue
            ent.program_ids.append(pid)

    found: set[str] = set()
    for code in re.findall(r"(?<![\d.,])(\d{3})(?![\d.,])", norm):
        if code in codes:
            found.update(m["major_id"] for m in majors if m["major_code"] == code)

    masked = f" {flat} "
    for alias, ids in _major_aliases():
        pattern = rf"(?<![a-z0-9]){re.escape(alias)}(?![a-z0-9])"
        if re.search(pattern, masked):
            found.update(ids)
            masked = re.sub(pattern, " ", masked)
    for alias, target in CASE_SENSITIVE_ALIASES.items():
        if re.search(rf"(?<![A-Za-z]){alias}(?![A-Za-z])", text):
            t = normalize(target)
            found.update(m["major_id"] for m in majors if t in normalize(m["name"]))

    if ent.program_ids and found:
        narrowed = [mid for mid in found if mid.split(":")[0] in ent.program_ids]
        found = set(narrowed) or found
    ent.major_ids = sorted(found)

    ly = latest_year()
    years = {int(y) for y in re.findall(r"\b(20[12]\d)\b", norm)}
    if re.search(r"nam nay|nam hien tai|moi nhat|gan nhat|hien nay", flat):
        years.add(ly)
    if re.search(r"nam ngoai|nam truoc|nam roi", flat):
        years.add(ly - 1)
    ent.years = sorted(years)

    for method, pat in METHOD_PATTERNS:
        if re.search(pat, flat):
            ent.methods.append(method)

    for m in re.findall(r"(?<![\d.,])(\d{2}(?:[.,]\d{1,2})?)\s*(?:diem|d\b)", flat):
        v = float(m.replace(",", "."))
        if 40 <= v <= 100:
            ent.mentioned_scores.append(v)
    return ent


# ──────────────────────────────────────────────
# Fact queries (exposed as agent / MCP tools)
# ──────────────────────────────────────────────
def _in(col: str, values: list) -> tuple[str, list]:
    if not values:
        return "", []
    return f" AND {col} IN ({','.join('?' * len(values))})", list(values)


def get_admission_scores(major_ids: list[str], years: list[int] | None = None,
                         methods: list[str] | None = None) -> list[dict]:
    w1, p1 = _in("s.major_id", major_ids)
    w2, p2 = _in("s.year", years or [])
    w3, p3 = _in("s.method", methods or [])
    return query(
        "SELECT s.year, s.method, s.score, s.major_code, s.program_id, m.name AS major_name, "
        "p.name AS program_name, s.source, s.source_url FROM admission_scores s "
        "JOIN majors m USING(major_id) JOIN programs p ON p.program_id = s.program_id WHERE 1=1"
        + w1 + w2 + w3 + " ORDER BY s.program_id, s.major_code, s.year, s.method",
        p1 + p2 + p3,
    )


def get_quotas(major_ids: list[str], year: int | None = None) -> list[dict]:
    w1, p1 = _in("q.major_id", major_ids)
    rows = query(
        "SELECT q.year, q.quota, q.scope, q.major_code, q.program_id, m.name AS major_name, "
        "p.name AS program_name, q.source_url FROM quotas q JOIN majors m USING(major_id) "
        "JOIN programs p ON p.program_id = q.program_id WHERE 1=1" + w1 + " ORDER BY q.program_id, q.major_code",
        p1,
    )
    return [r for r in rows if year is None or r["year"] == year]


def get_major_profiles(major_ids: list[str]) -> list[dict]:
    w, p = _in("m.major_id", major_ids)
    majors = query("SELECT m.*, pr.name AS program_name FROM majors m JOIN programs pr USING(program_id) WHERE 1=1" + w, p)
    for m in majors:
        mid = m["major_id"]
        m["subject_combinations"] = [r["combination"] for r in
                                     query("SELECT combination FROM subject_combinations WHERE major_id=?", [mid])]
        m["partner_universities"] = [f"{r['university']} ({r['country']})" for r in
                                     query("SELECT university, country FROM partner_universities WHERE major_id=?", [mid])]
    return majors


def get_tuition(program_ids: list[str] | None = None, academic_year: str | None = None) -> list[dict]:
    rows = query("SELECT * FROM tuition ORDER BY program_group, academic_year")
    if program_ids:
        rows = [r for r in rows if set(r["program_ids"].split(";")) & set(program_ids)] or rows
    if academic_year:
        rows = [r for r in rows if r["academic_year"] == academic_year] or rows
    return rows


def get_english_conversion() -> list[dict]:
    return query("SELECT * FROM english_conversion")


def get_timeline() -> list[dict]:
    return query('SELECT year, "when", event, source_url FROM admission_timeline')


def list_majors(program_ids: list[str] | None = None) -> list[dict]:
    w, p = _in("program_id", program_ids or [])
    return query("SELECT major_id, major_code, program_id, name, is_new FROM majors WHERE 1=1" + w +
                 " ORDER BY program_id, major_code", p)


# ──────────────────────────────────────────────
# Deterministic calculators
# ──────────────────────────────────────────────
def compute_admission_score(
    thpt_math: float, thpt_subject2: float, thpt_subject3: float,
    hocba_math: float, hocba_subject2: float, hocba_subject3: float,
    dgnl: float | None = None, bonus_points: float = 0.0, priority_points_30: float = 0.0,
) -> dict:
    """Xét tuyển Tổng hợp 2026 (đối tượng 2.1 / 2.2) — official formula, thang 100.

    thpt_*: điểm thi TN THPT (thang 10); hocba_*: TB lớp 10-11-12 từng môn (thang 10);
    dgnl: điểm ĐGNL ĐHQG-HCM đã nhân hệ số Toán (thang 1500); bonus_points: điểm cộng thành tích (≤10);
    priority_points_30: điểm ưu tiên khu vực + đối tượng theo thang 30 (≤2.75).
    """
    for v in (thpt_math, thpt_subject2, thpt_subject3, hocba_math, hocba_subject2, hocba_subject3):
        if not 0 <= v <= 10:
            raise ValueError("Điểm môn phải nằm trong thang 0–10.")
    if dgnl is not None and not 0 <= dgnl <= 1500:
        raise ValueError("Điểm ĐGNL (đã nhân hệ số Toán) phải nằm trong thang 0–1500.")
    thpt_qd = (2 * thpt_math + thpt_subject2 + thpt_subject3) / 4 * 10
    hocba_qd = (2 * hocba_math + hocba_subject2 + hocba_subject3) / 4 * 10
    nang_luc = dgnl / 15 if dgnl is not None else thpt_qd * 0.75
    hoc_luc = nang_luc * 0.7 + thpt_qd * 0.2 + hocba_qd * 0.1
    cong = min(max(bonus_points, 0.0), 10.0)
    if hoc_luc + cong >= 100:
        cong = 100 - hoc_luc
    ut_qd = min(max(priority_points_30, 0.0), 2.75) / 3 * 10
    uu_tien = ut_qd if hoc_luc + cong < 75 else round((100 - hoc_luc - cong) / 25 * ut_qd, 2)
    total = hoc_luc + cong + uu_tien
    return {
        "doi_tuong": "2.1 (có ĐGNL)" if dgnl is not None else "2.2 (không có ĐGNL)",
        "diem_nang_luc": round(nang_luc, 2), "diem_tnthpt_quy_doi": round(thpt_qd, 2),
        "diem_hoc_thpt_quy_doi": round(hocba_qd, 2), "diem_hoc_luc": round(hoc_luc, 2),
        "diem_cong": round(cong, 2), "diem_uu_tien": round(uu_tien, 2), "diem_xet_tuyen": round(total, 2),
        "cong_thuc": "Điểm xét tuyển = Học lực + Cộng + Ưu tiên; Học lực = Năng lực×70% + TNTHPT quy đổi×20% + Học THPT quy đổi×10%",
        "source_url": "https://hcmut.edu.vn/tuyen-sinh/dai-hoc-chinh-quy/phuong-thuc-tuyen-sinh/xet-tuyen-tong-hop-2026",
    }


def recommend_majors(score: float, major_ids: list[str] | None = None, program_ids: list[str] | None = None,
                     limit: int = 8) -> dict:
    """Compare a composite score with the latest TH cut-offs → bands an toàn / vừa sức / thử thách."""
    year = latest_year()
    w1, p1 = _in("s.major_id", major_ids or [])
    w2, p2 = _in("s.program_id", program_ids or [])
    rows = query(
        "SELECT s.major_id, s.major_code, s.program_id, s.score AS cutoff, m.name AS major_name, "
        "p.name AS program_name, (SELECT score FROM admission_scores x WHERE x.major_id=s.major_id "
        "AND x.method='TH' AND x.year=s.year-1) AS prev_cutoff FROM admission_scores s "
        "JOIN majors m USING(major_id) JOIN programs p ON p.program_id=s.program_id "
        "WHERE s.method='TH' AND s.year=?" + w1 + w2,
        [year] + p1 + p2,
    )

    def band(delta: float) -> str:
        if delta >= 3:
            return "an_toan"
        if delta >= -1:
            return "vua_suc"
        if delta >= -4:
            return "thu_thach"
        return "kho"

    for r in rows:
        r["delta"] = round(score - r["cutoff"], 2)
        r["band"] = band(r["delta"])
        r["trend"] = None if r["prev_cutoff"] is None else round(r["cutoff"] - r["prev_cutoff"], 2)
    order = {"vua_suc": 0, "an_toan": 1, "thu_thach": 2, "kho": 3}
    rows.sort(key=lambda r: (order[r["band"]], -r["cutoff"]))
    return {"score": score, "reference_year": year, "method": "TH", "results": rows[:limit],
            "disclaimer": "Chỉ mang tính tham khảo dựa trên điểm chuẩn các năm trước; không cam kết trúng tuyển."}
